"""add organization and app_user

Revision ID: 338389a07687
Revises: e2982cb4dc17
Create Date: 2026-07-22 23:41:37.225791
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '338389a07687'
down_revision: str | None = 'e2982cb4dc17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_tenant_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_feishu_tenant_key'), ['feishu_tenant_key'], unique=True)

    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('feishu_open_id', sa.String(length=64), nullable=False),
    sa.Column('feishu_union_id', sa.String(length=64), nullable=True),
    sa.Column('feishu_user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_feishu_open_id'), ['feishu_open_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_user_feishu_union_id'), ['feishu_union_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_org_id'))
        batch_op.drop_index(batch_op.f('ix_app_user_feishu_union_id'))
        batch_op.drop_index(batch_op.f('ix_app_user_feishu_open_id'))

    op.drop_table('app_user')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_feishu_tenant_key'))

    op.drop_table('organization')
    # ### end Alembic commands ###
