"""tenant isolation + audit columns

Revision ID: 5f8fc672f4d6
Revises: 338389a07687
Create Date: 2026-07-22 23:53:32.114325
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5f8fc672f4d6'
down_revision: str | None = '338389a07687'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidates_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interview_evaluations_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('interview_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interview_invitations_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('interview_outlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interview_outlines_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_position_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_position_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_operation_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('position_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_position_matches_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('resume_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resume_source_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_source_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('position_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_matches_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_actor_user_id'))
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('actor_user_id')

    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_position_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_job_position_owner_id'))
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('interview_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_outlines_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('interview_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_invitations_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_evaluations_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_owner_id'))
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
