"""initial schema

Revision ID: 7d8149b30d99
Revises: 
Create Date: 2026-05-20 12:08:11.803692
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7d8149b30d99'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_plain', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_masked', sa.String(length=64), nullable=True),
    sa.Column('email_plain', sa.String(length=128), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('email_masked', sa.String(length=128), nullable=True),
    sa.Column('current_city', sa.String(length=128), nullable=True),
    sa.Column('highest_degree', sa.String(length=64), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_position', sa.String(length=255), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_dedup_key'), 'candidate', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_candidate_email_hash'), 'candidate', ['email_hash'], unique=False)
    op.create_index(op.f('ix_candidate_name'), 'candidate', ['name'], unique=False)
    op.create_index(op.f('ix_candidate_phone_hash'), 'candidate', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_candidate_status'), 'candidate', ['status'], unique=False)
    op.create_table('export_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_record_created_at'), 'export_record', ['created_at'], unique=False)
    op.create_table('job_position',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('degree_requirement', sa.String(length=64), nullable=True),
    sa.Column('experience_min_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('experience_max_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_position_job_name'), 'job_position', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_position_status'), 'job_position', ['status'], unique=False)
    op.create_table('operation_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_audit_log_action'), 'operation_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_operation_audit_log_created_at'), 'operation_audit_log', ['created_at'], unique=False)
    op.create_table('platform_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('login_state_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'account_name', name='uk_platform_account')
    )
    op.create_index(op.f('ix_platform_account_platform_code'), 'platform_account', ['platform_code'], unique=False)
    op.create_table('crawl_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=True),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('query_keyword', sa.String(length=255), nullable=True),
    sa.Column('query_city', sa.String(length=128), nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_task_next_run_at'), 'crawl_task', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_task_platform_code'), 'crawl_task', ['platform_code'], unique=False)
    op.create_index(op.f('ix_crawl_task_status'), 'crawl_task', ['status'], unique=False)
    op.create_table('crawl_task_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_task_log_created_at'), 'crawl_task_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_task_log_task_id'), 'crawl_task_log', ['task_id'], unique=False)
    op.create_table('raw_resume',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('source_resume_id', sa.String(length=128), nullable=True),
    sa.Column('source_candidate_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_html_path', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parsed_status', sa.String(length=32), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'source_resume_id', name='uk_raw_resume_platform_source')
    )
    op.create_index(op.f('ix_raw_resume_content_hash'), 'raw_resume', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_resume_task_id'), 'raw_resume', ['task_id'], unique=False)
    op.create_table('boss_candidate_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('target_site', sa.String(length=64), nullable=False),
    sa.Column('candidate_key', sa.String(length=64), nullable=False),
    sa.Column('candidate_signature', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('resume_file_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_resume_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_resume_id'], ['raw_resume.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'candidate_key', name='uk_boss_platform_candidate_key')
    )
    op.create_index(op.f('ix_boss_candidate_record_candidate_key'), 'boss_candidate_record', ['candidate_key'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_content_hash'), 'boss_candidate_record', ['content_hash'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_job_title'), 'boss_candidate_record', ['job_title'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_name'), 'boss_candidate_record', ['name'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_platform_code'), 'boss_candidate_record', ['platform_code'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_raw_resume_id'), 'boss_candidate_record', ['raw_resume_id'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_target_site'), 'boss_candidate_record', ['target_site'], unique=False)
    op.create_index(op.f('ix_boss_candidate_record_task_id'), 'boss_candidate_record', ['task_id'], unique=False)
    op.create_table('platform_candidate_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('target_site', sa.String(length=64), nullable=False),
    sa.Column('candidate_key', sa.String(length=64), nullable=False),
    sa.Column('candidate_signature', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('resume_file_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_resume_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_resume_id'], ['raw_resume.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'candidate_key', name='uk_platform_candidate_key')
    )
    op.create_index(op.f('ix_platform_candidate_record_candidate_key'), 'platform_candidate_record', ['candidate_key'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_content_hash'), 'platform_candidate_record', ['content_hash'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_job_title'), 'platform_candidate_record', ['job_title'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_name'), 'platform_candidate_record', ['name'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_platform_code'), 'platform_candidate_record', ['platform_code'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_raw_resume_id'), 'platform_candidate_record', ['raw_resume_id'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_target_site'), 'platform_candidate_record', ['target_site'], unique=False)
    op.create_index(op.f('ix_platform_candidate_record_task_id'), 'platform_candidate_record', ['task_id'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_resume_id', sa.BigInteger(), nullable=True),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('resume_title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('expected_position', sa.String(length=255), nullable=True),
    sa.Column('expected_city', sa.String(length=128), nullable=True),
    sa.Column('expected_salary_min', sa.Integer(), nullable=True),
    sa.Column('expected_salary_max', sa.Integer(), nullable=True),
    sa.Column('expected_industry', sa.String(length=255), nullable=True),
    sa.Column('job_status', sa.String(length=64), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_status', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['raw_resume_id'], ['raw_resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_candidate_id'), 'resume', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_expected_position'), 'resume', ['expected_position'], unique=False)
    op.create_index(op.f('ix_resume_platform_code'), 'resume', ['platform_code'], unique=False)
    op.create_index(op.f('ix_resume_resume_status'), 'resume', ['resume_status'], unique=False)
    op.create_table('education_experience',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_experience_resume_id'), 'education_experience', ['resume_id'], unique=False)
    op.create_index(op.f('ix_education_experience_school_name'), 'education_experience', ['school_name'], unique=False)
    op.create_table('export_record_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_record_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['export_record_id'], ['export_record.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_record_item_candidate_id'), 'export_record_item', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_export_record_item_export_record_id'), 'export_record_item', ['export_record_id'], unique=False)
    op.create_table('project_experience',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibility', sa.Text(), nullable=True),
    sa.Column('achievement', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_experience_resume_id'), 'project_experience', ['resume_id'], unique=False)
    op.create_table('resume_attachment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_resume_id', sa.BigInteger(), nullable=True),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_ext', sa.String(length=32), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_resume_id'], ['raw_resume.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_attachment_file_hash'), 'resume_attachment', ['file_hash'], unique=False)
    op.create_index(op.f('ix_resume_attachment_resume_id'), 'resume_attachment', ['resume_id'], unique=False)
    op.create_table('resume_score',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('job_position_id', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('salary_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('city_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('matched_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_position_id', name='uk_resume_score')
    )
    op.create_index(op.f('ix_resume_score_job_position_id'), 'resume_score', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_resume_score_resume_id'), 'resume_score', ['resume_id'], unique=False)
    op.create_table('resume_skill',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('skill_level', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_skill_resume_id'), 'resume_skill', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skill_skill_name'), 'resume_skill', ['skill_name'], unique=False)
    op.create_table('resume_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_name', sa.String(length=128), nullable=False),
    sa.Column('tag_type', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_tag_resume_id'), 'resume_tag', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_tag_tag_name'), 'resume_tag', ['tag_name'], unique=False)
    op.create_table('work_experience',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_company_name'), 'work_experience', ['company_name'], unique=False)
    op.create_index(op.f('ix_work_experience_resume_id'), 'work_experience', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experience_resume_id'), table_name='work_experience')
    op.drop_index(op.f('ix_work_experience_company_name'), table_name='work_experience')
    op.drop_table('work_experience')
    op.drop_index(op.f('ix_resume_tag_tag_name'), table_name='resume_tag')
    op.drop_index(op.f('ix_resume_tag_resume_id'), table_name='resume_tag')
    op.drop_table('resume_tag')
    op.drop_index(op.f('ix_resume_skill_skill_name'), table_name='resume_skill')
    op.drop_index(op.f('ix_resume_skill_resume_id'), table_name='resume_skill')
    op.drop_table('resume_skill')
    op.drop_index(op.f('ix_resume_score_resume_id'), table_name='resume_score')
    op.drop_index(op.f('ix_resume_score_job_position_id'), table_name='resume_score')
    op.drop_table('resume_score')
    op.drop_index(op.f('ix_resume_attachment_resume_id'), table_name='resume_attachment')
    op.drop_index(op.f('ix_resume_attachment_file_hash'), table_name='resume_attachment')
    op.drop_table('resume_attachment')
    op.drop_index(op.f('ix_project_experience_resume_id'), table_name='project_experience')
    op.drop_table('project_experience')
    op.drop_index(op.f('ix_export_record_item_export_record_id'), table_name='export_record_item')
    op.drop_index(op.f('ix_export_record_item_candidate_id'), table_name='export_record_item')
    op.drop_table('export_record_item')
    op.drop_index(op.f('ix_education_experience_school_name'), table_name='education_experience')
    op.drop_index(op.f('ix_education_experience_resume_id'), table_name='education_experience')
    op.drop_table('education_experience')
    op.drop_index(op.f('ix_resume_resume_status'), table_name='resume')
    op.drop_index(op.f('ix_resume_platform_code'), table_name='resume')
    op.drop_index(op.f('ix_resume_expected_position'), table_name='resume')
    op.drop_index(op.f('ix_resume_candidate_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_platform_candidate_record_task_id'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_target_site'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_raw_resume_id'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_platform_code'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_name'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_job_title'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_content_hash'), table_name='platform_candidate_record')
    op.drop_index(op.f('ix_platform_candidate_record_candidate_key'), table_name='platform_candidate_record')
    op.drop_table('platform_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_task_id'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_target_site'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_raw_resume_id'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_platform_code'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_name'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_job_title'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_content_hash'), table_name='boss_candidate_record')
    op.drop_index(op.f('ix_boss_candidate_record_candidate_key'), table_name='boss_candidate_record')
    op.drop_table('boss_candidate_record')
    op.drop_index(op.f('ix_raw_resume_task_id'), table_name='raw_resume')
    op.drop_index(op.f('ix_raw_resume_content_hash'), table_name='raw_resume')
    op.drop_table('raw_resume')
    op.drop_index(op.f('ix_crawl_task_log_task_id'), table_name='crawl_task_log')
    op.drop_index(op.f('ix_crawl_task_log_created_at'), table_name='crawl_task_log')
    op.drop_table('crawl_task_log')
    op.drop_index(op.f('ix_crawl_task_status'), table_name='crawl_task')
    op.drop_index(op.f('ix_crawl_task_platform_code'), table_name='crawl_task')
    op.drop_index(op.f('ix_crawl_task_next_run_at'), table_name='crawl_task')
    op.drop_table('crawl_task')
    op.drop_index(op.f('ix_platform_account_platform_code'), table_name='platform_account')
    op.drop_table('platform_account')
    op.drop_index(op.f('ix_operation_audit_log_created_at'), table_name='operation_audit_log')
    op.drop_index(op.f('ix_operation_audit_log_action'), table_name='operation_audit_log')
    op.drop_table('operation_audit_log')
    op.drop_index(op.f('ix_job_position_status'), table_name='job_position')
    op.drop_index(op.f('ix_job_position_job_name'), table_name='job_position')
    op.drop_table('job_position')
    op.drop_index(op.f('ix_export_record_created_at'), table_name='export_record')
    op.drop_table('export_record')
    op.drop_index(op.f('ix_candidate_status'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_phone_hash'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_name'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_email_hash'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_dedup_key'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
