"""baseline unified sqlite schema

Revision ID: e2982cb4dc17
Revises: 
Create Date: 2026-07-22 16:30:12.120818
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e2982cb4dc17'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('endpoint_name', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('is_failover', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_log_feature'), ['feature'], unique=False)

    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('current_city', sa.String(length=50), nullable=True),
    sa.Column('education_level', sa.String(length=20), nullable=True),
    sa.Column('self_intro', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('name', 'age', 'education_level', name='uq_candidate_dedup_fallback'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_is_favorite'), ['is_favorite'], unique=False)

    op.create_table('job_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('work_city', sa.String(length=128), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('min_education', sa.String(length=64), nullable=True),
    sa.Column('min_experience', sa.String(length=64), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('job_requirements', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_position_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_position_title'), ['title'], unique=False)

    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_created_at'), ['created_at'], unique=False)

    op.create_table('platform_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('login_state_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'account_name', name='uk_platform_account')
    )
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_account_platform_code'), ['platform_code'], unique=False)

    op.create_table('crawl_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=True),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('query_keyword', sa.String(length=255), nullable=True),
    sa.Column('query_city', sa.String(length=128), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('planned_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_task_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_task_platform_code'), ['platform_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_task_status'), ['status'], unique=False)

    op.create_table('education',
    sa.Column('edu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('education_level', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_full_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edu_id')
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_education_level'), ['education_level'], unique=False)

    op.create_table('honors',
    sa.Column('honor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('honor_name', sa.String(length=200), nullable=False),
    sa.Column('honor_date', sa.Date(), nullable=True),
    sa.Column('honor_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('honor_id')
    )
    with op.batch_alter_table('honors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_honors_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('interview_evaluations',
    sa.Column('eval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('interviewer', sa.String(length=50), nullable=True),
    sa.Column('interview_round', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('interview_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_evaluations_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('interview_invitations',
    sa.Column('invitation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    with op.batch_alter_table('interview_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_invitations_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_invitations_status'), ['status'], unique=False)

    op.create_table('job_intention',
    sa.Column('intention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('target_position', sa.String(length=100), nullable=True),
    sa.Column('target_city', sa.String(length=50), nullable=True),
    sa.Column('expected_salary', sa.String(length=50), nullable=True),
    sa.Column('job_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intention_id')
    )
    with op.batch_alter_table('job_intention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_intention_candidate_id'), ['candidate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_intention_target_position'), ['target_position'], unique=False)

    op.create_table('position_matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('skill_match', sa.Integer(), nullable=True),
    sa.Column('experience_match', sa.Integer(), nullable=True),
    sa.Column('education_match', sa.Integer(), nullable=True),
    sa.Column('location_match', sa.Integer(), nullable=True),
    sa.Column('jd_hash', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['job_position.id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('position_id', 'candidate_id', name='uq_pos_cand_match')
    )
    with op.batch_alter_table('position_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_matches_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_matches_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_matches_score'), ['score'], unique=False)

    op.create_table('project_experience',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_role', sa.String(length=100), nullable=True),
    sa.Column('project_date', sa.String(length=50), nullable=True),
    sa.Column('project_desc', sa.Text(), nullable=True),
    sa.Column('project_duty', sa.Text(), nullable=True),
    sa.Column('project_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('project_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_experience_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('resume_source',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sa.String(length=30), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('attachment_works_path', sa.Text(), nullable=True),
    sa.Column('crawl_time', sa.DateTime(), nullable=True),
    sa.Column('is_duplicate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('resume_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_source_candidate_id'), ['candidate_id'], unique=True)

    op.create_table('skills_certificates',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(length=20), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('is_core', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    with op.batch_alter_table('skills_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_certificates_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_certificates_skill_name'), ['skill_name'], unique=False)

    op.create_table('system_evaluation',
    sa.Column('eval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.String(length=5), nullable=True),
    sa.Column('match_position', sa.String(length=100), nullable=True),
    sa.Column('match_degree', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('interview_status', sa.String(length=20), nullable=True),
    sa.Column('interview_time', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eval_id')
    )
    with op.batch_alter_table('system_evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_evaluation_candidate_id'), ['candidate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_evaluation_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_evaluation_total_score'), ['total_score'], unique=False)

    op.create_table('work_experience',
    sa.Column('work_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('job_content', sa.Text(), nullable=True),
    sa.Column('is_main_job', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id')
    )
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_experience_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_experience_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_experience_position'), ['position'], unique=False)

    op.create_table('interview_outlines',
    sa.Column('outline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['interview_invitations.invitation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outline_id')
    )
    with op.batch_alter_table('interview_outlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_outlines_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_outlines_invitation_id'), ['invitation_id'], unique=True)

    op.create_table('raw_resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('source_resume_id', sa.String(length=128), nullable=True),
    sa.Column('source_candidate_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('raw_html_path', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parsed_status', sa.String(length=32), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_account.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'source_resume_id', name='uk_raw_resume_platform_source')
    )
    with op.batch_alter_table('raw_resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_resume_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_resume_task_id'), ['task_id'], unique=False)

    op.create_table('boss_candidate_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('target_site', sa.String(length=64), nullable=False),
    sa.Column('candidate_key', sa.String(length=64), nullable=False),
    sa.Column('candidate_signature', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('talking_position', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('resume_file_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_resume_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raw_resume_id'], ['raw_resume.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'candidate_key', name='uk_boss_platform_candidate_key')
    )
    with op.batch_alter_table('boss_candidate_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_candidate_key'), ['candidate_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_job_title'), ['job_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_platform_code'), ['platform_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_raw_resume_id'), ['raw_resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_target_site'), ['target_site'], unique=False)
        batch_op.create_index(batch_op.f('ix_boss_candidate_record_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boss_candidate_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_task_id'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_target_site'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_raw_resume_id'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_platform_code'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_name'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_job_title'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_content_hash'))
        batch_op.drop_index(batch_op.f('ix_boss_candidate_record_candidate_key'))

    op.drop_table('boss_candidate_record')
    with op.batch_alter_table('raw_resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_resume_task_id'))
        batch_op.drop_index(batch_op.f('ix_raw_resume_content_hash'))

    op.drop_table('raw_resume')
    with op.batch_alter_table('interview_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_outlines_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_interview_outlines_candidate_id'))

    op.drop_table('interview_outlines')
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_experience_position'))
        batch_op.drop_index(batch_op.f('ix_work_experience_industry'))
        batch_op.drop_index(batch_op.f('ix_work_experience_candidate_id'))

    op.drop_table('work_experience')
    with op.batch_alter_table('system_evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_evaluation_total_score'))
        batch_op.drop_index(batch_op.f('ix_system_evaluation_grade_level'))
        batch_op.drop_index(batch_op.f('ix_system_evaluation_candidate_id'))

    op.drop_table('system_evaluation')
    with op.batch_alter_table('skills_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_certificates_skill_name'))
        batch_op.drop_index(batch_op.f('ix_skills_certificates_candidate_id'))

    op.drop_table('skills_certificates')
    with op.batch_alter_table('resume_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_source_candidate_id'))

    op.drop_table('resume_source')
    with op.batch_alter_table('project_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_experience_candidate_id'))

    op.drop_table('project_experience')
    with op.batch_alter_table('position_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_matches_score'))
        batch_op.drop_index(batch_op.f('ix_position_matches_position_id'))
        batch_op.drop_index(batch_op.f('ix_position_matches_candidate_id'))

    op.drop_table('position_matches')
    with op.batch_alter_table('job_intention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_intention_target_position'))
        batch_op.drop_index(batch_op.f('ix_job_intention_candidate_id'))

    op.drop_table('job_intention')
    with op.batch_alter_table('interview_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_interview_invitations_candidate_id'))

    op.drop_table('interview_invitations')
    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_evaluations_candidate_id'))

    op.drop_table('interview_evaluations')
    with op.batch_alter_table('honors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_honors_candidate_id'))

    op.drop_table('honors')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_education_level'))
        batch_op.drop_index(batch_op.f('ix_education_candidate_id'))

    op.drop_table('education')
    with op.batch_alter_table('crawl_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_task_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_task_platform_code'))
        batch_op.drop_index(batch_op.f('ix_crawl_task_next_run_at'))

    op.drop_table('crawl_task')
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_account_platform_code'))

    op.drop_table('platform_account')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_log_action'))

    op.drop_table('operation_log')
    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_position_title'))
        batch_op.drop_index(batch_op.f('ix_job_position_status'))

    op.drop_table('job_position')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_is_favorite'))

    op.drop_table('candidates')
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_feature'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_created_at'))

    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
