apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recruitment-assistant.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recruitment-assistant.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
