apiVersion: v1
kind: Service
metadata:
  name: {{ include "recruitment-assistant.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recruitment-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "recruitment-assistant.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
